version: '2'

services:
  rabbitmq:
    image: rabbitmq:3-management
  mongo:
    image: mongo:3

  dev:
    build: .
    command: ./test.sh test
    volumes:
      - .:/go/src/github.com/getconversio/go-utils
    env_file: .env
    depends_on:
      - rabbitmq
      - mongo
